09.django/d0519_02/spjt/member/urls.py
from django.urls import include,path
from . import views

app_name='member'
urlpatterns = [
    path('list/',views.list,name='list'),
    path('login/',views.login,name='login'),
]

09.django/d0519_02/spjt/spjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('member/',include('member.urls')),
]

09.django/d0519_02/spjt/member/models.py
from django.db import models
from datetime import datetime


class Member(models.Model):
    m_no=models.AutoField(primary_key=True)
    m_id=models.CharField(max_length=100)
    m_pw=models.CharField(max_length=100)
    m_name=models.CharField(max_length=200)
    m_tel=models.CharField(max_length=13)
    m_zip=models.CharField(max_length=5)
    m_adress1=models.CharField(max_length=300)
    m_adress2=models.CharField(max_length=300)
    m_date=models.DateTimeField(default=datetime.now(),blank=True)
    
    
    def __str__(self):
        return self.m_id
    

09.django/d0519_02/spjt/home/views.py
from django.shortcuts import render

def index(request):
    
    return render(request,'index.html')

09.django/d0519_02/spjt/member/views.py
from django.shortcuts import render

def login(request):
    return render(request,'login.html')

def list(request):
    return render(request,'list.html')

09.django/d0519_02/spjt/home/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>메인페이지</title>
</head>
<body>
    <h2>메인페이지</h2>
    <ul>
        <a href="{% url 'member:list'%}"><li>회원정보리스트</li></a>
        <a href="{% url 'member:login'%}"><li>로그인</li></a>
    </ul>
</body>
</html>