semi_project_mygit/AdminPage/urls.py
from django.urls import path
from . import views
app_name='AdminPage'
urlpatterns = [
    path('',views.aboutus,name='index'),
    path('aboutus/',views.aboutus, name='aboutus'),
    
    #admin login 
    path('ad_login/',views.ad_login,name="ad_login"),
    #admin logout
    path('ad_logout/',views.ad_logout,name="ad_logout"),
    #문의사항페이지
    path('ad_contact_us/',views.ad_contact_us, name='ad_contact_us'),
    ###########################################################################################
    
    #admin회원list
    path('<str:searchword>/<str:category>/ad_m_L/',views.ad_m_L, name='ad_m_L'),
    #admin회원view
    path('<str:searchword>/<str:category>/<str:user_id>/ad_m_V/',views.ad_m_V, name='ad_m_V'),
    #admin회원update
    path('<str:searchword>/<str:category>/<str:user_id>/ad_m_U/',views.ad_m_U, name='ad_m_U'),
    #admin회원delete
    path('<str:searchword>/<str:category>/<str:user_id>/ad_m_D/',views.ad_m_D, name='ad_m_D'),
    ###########################################################################################
    
    
    #admin음식list
    path('<str:searchword2>/<str:category2>/ad_f_L/',views.ad_f_L, name='ad_f_L'),
    #admin음식view
    path('<str:searchword2>/<str:category2>/<str:f_NO>/ad_f_V/',views.ad_f_V, name='ad_f_V'),
    #admin음식update
    path('<str:searchword2>/<str:category2>/<str:f_NO>/ad_f_U/',views.ad_f_U, name='ad_f_U'),
    #admin음식delete
    path('<str:searchword2>/<str:category2>/<str:f_NO>/ad_f_D/',views.ad_f_D, name='ad_f_D'),
    
    
    ###########################################################################################

    #admin운동list
    path('<str:searchword3>/<str:category3>/ad_e_L/',views.ad_e_L, name='ad_e_L'),
    #admin운동view
    path('<str:searchword3>/<str:category3>/<str:ex_id>/ad_e_V/',views.ad_e_V, name='ad_e_V'),
    #admin운동delete
    path('<str:searchword3>/<str:category3>/<str:ex_id>/ad_e_D/',views.ad_e_D, name='ad_e_D'),
    #admin운동update
    path('<str:searchword3>/<str:category3>/<str:ex_id>/ad_e_U/',views.ad_e_U, name='ad_e_U'),
    
    
    ###########################################################################################
    
    #admin문의list
    path('<str:searchword4>/<str:category4>/ad_c_L/',views.ad_c_L, name='ad_c_L'),
    #admin문의view
    path('<str:searchword4>/<str:category4>/<str:c_No>/ad_c_V/',views.ad_c_V, name='ad_c_V'),
    #admin문의update
    path('<str:searchword4>/<str:category4>/<str:c_No>/ad_c_U/',views.ad_c_U, name='ad_c_U'),
    #admin문의delete
    path('<str:searchword4>/<str:category4>/<str:c_No>/ad_c_D/',views.ad_c_D, name='ad_c_D'),
    
    
    
    
]

semi_project_mygit/Home/urls.py
from django.urls import path
from . import views
app_name=''
urlpatterns = [
    path('',views.index,name='index'),
]

semi_project_mygit/sChoice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls')),
    path('adminpage/',include('AdminPage.urls')),
    path('board/',include('Board.urls')),
    path('dailycheck/',include('DailyCheck.urls')),
    path('member/',include('Member.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

semi_project_mygit/AdminPage/models.py
from django.db import models

class Exercise(models.Model):
    # ex_no=models.AutoField()
    ex_id=models.CharField(max_length=10,primary_key=True) # 운동아이디
    # activity_Choice=(('bicycling','자전거'),('conditioning',''),('healthclub','헬스'),('running','러닝'),('sports',''),('walking','걷기'),('water','수상운동'),('winter','설상운동'))
    activity=models.CharField(max_length=1000,blank=True) # 운동종류
    # aerobic_Choice=(('o','유산소'),('x','무산소'))
    aerobic=models.CharField(max_length=1,blank=True) # 유산소, 무산소
    met=models.IntegerField(default=0,blank=True) # 에너지소모량
    # level_Choice=((2,'저강도 운동'),(3,'중강도 운동'),(6,'고강도 운동')) # 운동강도
    level = models.IntegerField(default=0,blank=True) # 운동강도
    ex_name=models.CharField(max_length=1000,blank=True) # 운동이름
    # target_Choice=(('Abs','코어'),('Arms','팔'),('Back','등'),('Chest','가슴'),('Legs','하체'),('Shoulders','어깨')) # 운동강도
    target_category=models.CharField(max_length=1000,blank=True) # 타켓 카테고리
    muscle=models.CharField(max_length=1000,blank=True) # 자극되는 근육
    equipment=models.CharField(max_length=1000,blank=True) # 운동에 사용되는 운동기구
    imgUrl=models.ImageField(blank=True,upload_to="images") # 운동 자세 이미지 주소
    
    
    
class Food(models.Model):
    
    f_NO = models.AutoField(primary_key=True) #음식번호
    f_id = models.CharField(max_length=100,blank=True) #음식아이디
    f_DB = models.CharField(max_length=100,blank=True) #음식DB군
    f_name = models.CharField(max_length=100,blank=True) #음식이름
    f_por = models.IntegerField(default=0,blank=True) #1회제공량 
    f_carb = models.FloatField(default=0,blank=True) #탄수화물
    f_protein = models.FloatField(default=0,blank=True) #단백질
    f_fat = models.FloatField(default=0,blank=True) #지방
    
    
class ContactUs(models.Model):
    c_No=models.AutoField(primary_key=True)
    c_name=models.CharField(max_length=100,null=True,blank=True)
    c_email=models.CharField(max_length=1000,null=True,blank=True)
    c_tel=models.CharField(max_length=13,null=True,blank=True)
    c_title=models.CharField(max_length=1000,null=True,blank=True)
    c_content=models.TextField(null=True,blank=True)
    

semi_project_mygit/AdminPage/views.py
import datetime
from django.shortcuts import render,redirect
from Member.models import Members
from AdminPage.models import Food,Exercise,ContactUs
from django.db.models import Q


#어바웃어스
def aboutus(request):
    return render(request,'aboutus.html')



#Admin login
def ad_login(request):
    if request.method=='GET':
        return render(request,'ad_login.html')
    
    else: 
        user_id = request.POST.get('user_id')
        user_pw = request.POST.get('user_pw')
        
        if user_id == 'admin' and user_pw =='1234':
        
            try:
                qs = Members.objects.get(user_id=user_id,user_pw=user_pw)
                
            except Members.DoesNotExist: 
                qs = None 
                
            if qs:
                request.session['session_user_id']=qs.user_id
                request.session['session_user_name']=qs.user_name
               
                
                
                return render(request,'ad_m_L.html')
            else:
                
                msg="관리자만 로그인이 가능합니다."
                
         
                return render(request,'ad_login.html',{'msg':msg})
            
        else:
            msg="관리자만 로그인이 가능합니다."
            return render(request,'ad_login.html',{'msg':msg})
        
    
#Admin logout
def ad_logout(request):
    request.session.clear()
    return redirect('/') 
    


#Admin Contact Us 
def ad_contact_us(request):
    
    
    if request.method == 'GET':
        
        return render(request,'ad_contact_us.html')
    
    elif request.method == 'POST':
        
        c_name = request.POST.get('c_name',None)
        c_email = request.POST.get('c_email',None)
        c_tel = request.POST.get('c_tel',None)
        c_title = request.POST.get('c_title',None)
        c_content = request.POST.get('c_content',None)
        
        contact_us = ContactUs(c_name=c_name,c_email=c_email,c_tel=c_tel,c_title=c_title,c_content=c_content)
        
        contact_us.save()
        
        return redirect('/')


#Admin MEMBER List
def ad_m_L(request,searchword,category):
    
    if request.method == 'POST':
        category = request.POST.get('category')
        searchword = request.POST.get('searchword')
        
    if category == 'category':
            qs = Members.objects.all().order_by('-user_name')
        

    elif category == 'user_name':
        qs = Members.objects.filter(user_name__contains=searchword).order_by('-user_name')
        
          
    elif category == 'user_id':
        qs = Members.objects.filter(user_id__contains=searchword).order_by('-user_name')
        
        
        
    elif category == 'email':
        qs = Members.objects.filter(email__contains=searchword).order_by('-user_name')
        
        
    else:
        qs = Members.objects.filter(Q(user_name__contains=searchword)|Q(user_id__contains=searchword)|Q(user_name__contains=searchword)).order_by('-user_name')
        
        
    context ={'admin_List':qs,'searchword':searchword,'category':category}
    
    return render(request,'ad_m_L.html',context)




#Admin MEMBER View
def ad_m_V(request,user_id,searchword,category):
    
    qs = Members.objects.get(user_id=user_id)
    
    
    context ={'admin_List':qs,'searchword':searchword,'category':category,'user_id':user_id}
  
    

    return render(request,'ad_m_V.html',context)


#Admin MEMBER Delete
def ad_m_D(request,user_id,searchword,category):
    
    qs = Members.objects.get(user_id=user_id)
    qs.delete()
    return redirect('AdminPage:ad_m_L',searchword,category)
    
    



#Admin MEMEBER Update
def ad_m_U(request,user_id,searchword,category):
    
    if request.method == 'GET':
        qs = Members.objects.get(user_id=user_id)
        
        context = {'ad_List':qs,'searchword':searchword,'category':category,'user_id':user_id}
        
        return render(request,'ad_m_U.html',context)
    
    else:
        qs = Members.objects.get(user_id=user_id)
        
        qs.user_name = request.POST.get('username')
        qs.pro = request.POST.get('advancelevel')
        
        year  = int(request.POST.get('year'))
        month = int(request.POST.get('month'))
        day  = int(request.POST.get('day'))
        
        qs.birth = datetime.date(year,month,day)
        qs.gender  = request.POST.get('gender')
        qs.phone = request.POST.get('tel')
        qs.email  = request.POST.get('email')
        qs.zipcode = request.POST.get('postcode')
        qs.addressd1 = request.POST.get('address')
        qs.addressd2 = request.POST.get('detailAddress')
        qs.addressd3 = request.POST.get('extraAddress')
        qs.service= request.POST.get('service')
        qs.user_purpose = request.POST.get('purpose')
        qs.user_target = request.POST.get('target')
        qs.vegan = request.POST.get('vegan')
        qs.allergic_food  = request.POST.get('allergic_food')
        qs.goal_weight = request.POST.get('goal_weight')
        qs.goal_bodyfat= request.POST.get('goal_bodyfat')
        qs.goal_period = request.POST.get('goal_period')
        
        qs.save()
        
        return redirect('AdminPage:ad_m_L',searchword,category)
    
###################################################################################
#admin FOOD List
def ad_f_L(request,searchword2,category2):
    
    if request.method == 'POST':
        category2 = request.POST.get('category2')
        searchword2 = request.POST.get('searchword2')
        
    # if category2 == 'category2':
    #     qs = Food.objects.all().order_by('-f_NO')
        
    if category2 == 'f_NO':
        qs = Food.objects.filter(f_NO__contains=searchword2).order_by('-f_NO')
        
          
    elif category2 == 'f_name':
        qs = Food.objects.filter(f_name__contains=searchword2).order_by('-f_NO')
        
        
        
    elif category2 == 'f_DB':
        qs = Food.objects.filter(f_DB__contains=searchword2).order_by('-f_NO')
        
        
    else:
        qs = Food.objects.filter(Q(f_NO__contains=searchword2)|Q(f_name__contains=searchword2)|Q(f_DB__contains=searchword2)).order_by('-f_NO')
        
        
    context ={'food_List':qs,'searchword2':searchword2,'category2':category2}
    
    return render(request,'ad_f_L.html',context)



#Admin Food View
def ad_f_V(request,f_NO,searchword2,category2):
    
    qs = Food.objects.get(f_NO=f_NO)
    
    
    context ={'Food_List':qs,'searchword2':searchword2,'category2':category2,'f_NO':f_NO}
    

    return render(request,'ad_f_V.html',context)



#Admin Food Update
def ad_f_U(request,f_NO,searchword2,category2):
    
    if request.method == 'GET':
        qs = Food.objects.get(f_NO=f_NO)
        
        context = {'food_List':qs,'searchword2':searchword2,'category2':category2,'f_NO':f_NO}
        
        return render(request,'ad_f_U.html',context)
    
    else:
        qs = Food.objects.get(f_NO=f_NO)
        
        qs.f_id = request.POST.get('f_id')
        qs.f_DB = request.POST.get('f_DB')
        qs.f_name  = request.POST.get('f_name')
        qs.f_por = request.POST.get('f_por')
        qs.f_carb  = request.POST.get('f_carb')
        qs.f_protein = request.POST.get('f_protein')
        qs.f_fat = request.POST.get('f_fat')
        
        qs.save()
        
        return redirect('AdminPage:ad_f_L',searchword2,category2)


#Admin Food Delete
def ad_f_D(request,f_NO,searchword2,category2):
    
    qs = Food.objects.get(f_NO=f_NO)
    
    print('@@@@@@@@@@@@@@@@@@@:',qs)
    
    qs.delete()
    
    return redirect('AdminPage:ad_f_L',searchword2,category2)   
    

###################################################################################
#admin EX List
def ad_e_L(request,searchword3,category3):
    
    if request.method == 'POST':
        category3 = request.POST.get('category3')
        searchword3 = request.POST.get('searchword3')
     
     
    if category3 == 'category3':
        qs = Exercise.objects.all().order_by('-ex_id')   
    
        
    elif category3 == 'ex_id':
        qs = Exercise.objects.filter(ex_id__contains=searchword3).order_by('-ex_id')
        
          
    elif category3 == 'ex_name':
        qs = Exercise.objects.filter(ex_name__contains=searchword3).order_by('-ex_id')
        
        
        
    elif category3 == 'level':
        qs = Exercise.objects.filter(level__contains=searchword3).order_by('-ex_id')
        
        
    else:
        qs = Exercise.objects.filter(Q(ex_id__contains=searchword3)|Q(ex_name__contains=searchword3)|Q(level__contains=searchword3)).order_by('-ex_id')
        
        
    context ={'ex_List':qs,'searchword3':searchword3,'category3':category3}
    
    return render(request,'ad_e_L.html',context)


#Admin EX View
def ad_e_V(request,ex_id,searchword3,category3):
    
    qs = Exercise.objects.get(ex_id=ex_id)
    
    
    context ={'ex_List':qs,'searchword3':searchword3,'category3':category3,'ex_id':ex_id}
    

    return render(request,'ad_e_V.html',context)



#Admin EX Delete
def ad_e_D(request,ex_id,searchword,category):
    
    qs = Exercise.objects.get(ex_id=ex_id)
    qs.delete()
    return redirect('AdminPage:ad_e_L',searchword,category)



#Admin EX Update
def ad_e_U(request,ex_id,searchword3,category3):
    
    if request.method == 'GET':
        qs = Exercise.objects.get(ex_id=ex_id)
        
        context = {'ex_List':qs,'searchword3':searchword3,'category3':category3,'ex_id':ex_id}
        
        return render(request,'ad_e_U.html',context)
    
    else:
        qs = Exercise.objects.get(ex_id=ex_id)
        
        qs.activity = request.POST.get('activity')
        qs.aerobic = request.POST.get('aerobic')
        qs.met  = request.POST.get('met')
        qs.level = request.POST.get('level')
        qs.ex_name  = request.POST.get('ex_name')
        qs.target_category = request.POST.get('target_category')
        qs.muscle = request.POST.get('muscle')
        qs.equipment = request.POST.get('equipment')
        

semi_project_mygit/AdminPage/templates/ad_c_L.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>AdminPage</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static 'css/admin_list.css'%}">
	<script  src="http://code.jquery.com/jquery-latest.min.js"></script>
	<title>AdminPage</title>
	<script>
		
	
	
		function searchBtn(){
	
		if($('#searchword4').val()==''){
	
			alert('검색어를 입력하세요.')
			$('#searchword4').focus()
			return false 
			
		} 
	
		$('#searchfrm4').submit()
	
		}


  </script> 




</head>
<body>

	<nav>
  
		<ul class='nav_container'>
		  <li class='nav_item'><a href="/">UNNI'S CHOICE</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_m_L' searchword='searchword' category='category' %}">회원관리</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_f_L' searchword2='searchword2' category2='category2' %}">음식DB관리</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_e_L' searchword3='searchword3' category3='category3' %}">운동DB관리</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_c_L' searchword4='searchword4' category4='category4'%}">Contact-Us</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_logout'%}">로그아웃</a></li>
		</ul>
	  
	  </nav>



	<section class="main-content">
		<div class="container">

			<div class="admin_name">

				<h1>Contact Us-Admin</h1>

			</div>

			<div class="wrapper">
				<form action="{% url 'AdminPage:ad_c_L' searchword4='searchword4'  category4='category4' %}" name="searchfrm4" id='searchfrm4' method="post">
				  {% csrf_token %} 
				

				  <select class='admin_select' name="category4" id="category4">
					<option value="c_name">이름</option>
					<option value="c_title">제목</option>
					<option value="c_email">이메일</option>
					<option value="all">전체</option>
				  </select>
			
			
				  <div class="title">
					<input type="text" name='searchword4' id='searchword4' size="16">
				  <div>
					<button type="button" onclick='searchBtn()'><span>search</span></button>
				  </div>
				</form>
			  </div>


			<br>
			<br>

			<table class="table">
				<thead>

					<colgroup>
						<col width="12%">
						<col width="12%">
						<col width="12%">
						<col width="12%">
						<col width="12%">
						<col width="20%">
						<col width="12%">
					  </colgroup>

					<tr>
						<th>번호</th>
						<th>이름</th>
						<th>제목</th>
						<th>이메일</th>
						<th>전화번호</th>
						<th>내용</th>
						<th>actions</th>
					  </tr>
					
				</thead>
				<tbody>
					{% if contact_List %}
					{% for board in contact_List %}

					<script>

						function deleteBtn(){
							if(confirm('삭제하시겠습니까?')){

								location.href="{% url 'AdminPage:ad_c_D' searchword4='searchword4' category4='category4' c_No=board.c_No %}"

							
							}else{
				
								return false
							}
						}
					</script>
					<tr>
						<td>
							<div class="user-info">
								<div class="user-info__basic">
									<h6 class="mb-0"><a href="{% url 'AdminPage:ad_c_V' searchword4='searchword4' category4='category4' c_No=board.c_No %}">{{board.c_No}}</a></h6>
									
								</div>
							</div>
						</td>
						
						<td>
							<h6 class="mb-0">{{board.c_name}}</h6>
							
						</td>
						<td>
							<h6 class="mb-0">{{board.c_title}}</h6>
							
						</td>
						<td>
							<h6 class="mb-0">{{board.c_email}}</h6>
						</td>
						<td>
							<h6 class="mb-0">{{board.c_tel}}</h6>
						</td>
						<td>
							<h6 class="mb-0">{{board.c_content}}</h6>
						</td>

						<td>
							<div class="dropdown open">
								<a href="#!" class="px-2" id="triggerId1" data-toggle="dropdown" aria-haspopup="true"
										aria-expanded="false">
											<i class="fa fa-ellipsis-v"></i>
								</a>
								<div class="dropdown-menu" aria-labelledby="triggerId1">
									<a class="dropdown-item" href="{% url 'AdminPage:ad_c_U' searchword4=searchword4 category4=category4 c_No=board.c_No %}"><i class="fa fa-pencil mr-1"></i> Edit</a>
									<a class="dropdown-item text-danger" onclick='deleteBtn()'><i class="fa fa-trash mr-1"></i>Delete</a>
								</div>
							</div> 
					</tr>

					{% endfor %}
					{%else%}
					<tr>
					  <td colspan='6'>데이터가 없습니다</td>
					</tr>
					{% endif %}

				</tbody>
			</table>
		</div>
	</section>
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

semi_project_mygit/AdminPage/templates/ad_f_L.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>AdminPage</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static 'css/admin_list.css'%}">
	<script  src="http://code.jquery.com/jquery-latest.min.js"></script>
	<title>AdminPage</title>
	<script>
		
	
	
		function searchBtn(){
	
		if($('#searchword2').val()==''){
	
			alert('검색어를 입력하세요.')
			$('#searchword2').focus()
			return false 
			
		} 
	
		$('#searchfrm2').submit()
	
		}


  </script> 




</head>
<body>

	<nav>
  
		<ul class='nav_container'>
		  <li class='nav_item'><a href="/">UNNI'S CHOICE</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_m_L' searchword='searchword' category='category' %}">회원관리</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_f_L' searchword2='searchword2' category2='category2' %}">음식DB관리</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_e_L' searchword3='searchword3' category3='category3' %}">운동DB관리</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_c_L' searchword4='searchword4' category4='category4'%}">Contact-Us</a></li>
		  <li class='nav_item'><a href="{% url 'AdminPage:ad_logout'%}">로그아웃</a></li>
		</ul>
	  
	  </nav>



	<section class="main-content">
		<div class="container">

			<div class="admin_name">
				<h1>Food-Admin</h1>
			</div>

			<div class="wrapper">
				<form action="{% url 'AdminPage:ad_f_L' searchword2='searchword2'  category2='category2' %}" name="searchfrm2" id='searchfrm2' method="post">
				  {% csrf_token %} 
				  
				  <select class='admin_select' name="category2" id="category2">
					<option value="f_NO">음식번호</option>
					<option value="f_name">음식이름</option>
					<option value="f_DB">음식DB군</option>
					<option value="all">전체</option>
				  </select>
			
				  <div class="title">
					<input type="text" name='searchword2' id='searchword2' size="16">
				  <div>
					<button type="button" onclick='searchBtn()'><span>search</span></button>
				  </div>
				</form>
			  </div>


			<br>
			<br>

			<table class="table">
				<thead>

					<colgroup>
						<col width="24%">
						<col width="13%">
						<col width="13%">
						<col width="13%">
						<col width="13%">
						<col width="13%">
						<col width="13%">
						<col width="13%">
					  </colgroup>

					<tr>
						<th>음식이름</th>
						<th>음식번호</th>
						<th>음식DB군</th>
						<th>g당</th>
						<th>탄수화물</th>
						<th>단백질</th>
						<th>지방</th>
						<th>actions</th>
					  </tr>
					
				</thead>
				<tbody>
					{% if food_List %}
					{% for board in food_List %}

					<script>

						function deleteBtn(){
							if(confirm('삭제하시겠습니까?')){
				
								location.href="{% url 'AdminPage:ad_f_D' searchword2='searchword2' category2='category2'  f_NO=board.f_NO %}"

								alert('삭제되었습니다.')
								
							}else{
				
								return false
							}
						}
					</script>
					<tr>
						<td>
							<div class="user-info">
								<div class="user-info__img">
									<img src="/static/img/apple.png" alt="사과">
								</div>
								<div class="user-info__basic">
									<h6 class="mb-0"><a href="{% url 'AdminPage:ad_f_V' searchword2 category2 board.f_NO %}">{{board.f_name}}</a></h6>
									
								</div>
							</div>
						</td>
						
						<td>
							<h6 class="mb-0">{{board.f_NO}}</h6>
							
						</td>
						<td>
							<h6 class="mb-0">{{board.f_DB}}</h6>
							
						</td>
						<td>
							<h6 class="mb-0">{{board.f_por}}</h6>
						</td>
						<td>
							<h6 class="mb-0">{{board.f_carb}}</h6>
						</td>
						<td>
							<h6 class="mb-0">{{board.f_protein}}</h6>
						</td>
						<td>
							<h6 class="mb-0">{{board.f_fat}}</h6>
						</td>

						<td>
							<div class="dropdown open">
								<a href="#!" class="px-2" id="triggerId1" data-toggle="dropdown" aria-haspopup="true"
										aria-expanded="false">
											<i class="fa fa-ellipsis-v"></i>
								</a>
								<div class="dropdown-menu" aria-labelledby="triggerId1">
									<a class="dropdown-item" href="{% url 'AdminPage:ad_f_U' searchword2=searchword2 category2=category2  f_NO=board.f_NO %}"><i class="fa fa-pencil mr-1"></i> Edit</a>
									<a class="dropdown-item text-danger" onclick='deleteBtn()'><i class="fa fa-trash mr-1"></i>Delete</a>
								</div>
							</div>
						</td>
					</tr>

					{% endfor %}
					{%else%}
					<tr>
					  <td colspan='7'>데이터가 없습니다</td>
					</tr>
					{% endif %}

				</tbody>
			</table>
		</div>
	</section>
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>